# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigoEntrada',
            new_name='valorVenta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idSalida',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
