# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20171001_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
