# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20171001_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateField(verbose_name=b'01-10-17 22:41 29'),
        ),
    ]
