# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20171001_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaVenta',
            field=models.DateField(),
        ),
    ]
