# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20171002_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigoVenta',
            new_name='codigo_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fechaVenta',
            new_name='fecha_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='idProducto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='valorVenta',
            new_name='valor_venta',
        ),
    ]
