# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20171023_0308'),
        ('venta', '0008_auto_20171022_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigo_venta',
            new_name='codigoVenta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha_venta',
            new_name='fechaVenta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='valor_venta',
            new_name='valorVenta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='idProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
