# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_registro_id_producto'),
        ('venta', '0009_auto_20171023_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigoVenta',
            new_name='codigo_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fechaVenta',
            new_name='fecha_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='valorVenta',
            new_name='valor_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Registro'),
        ),
    ]
