# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_auto_20170928_0428'),
        ('distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigoCompra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valorCompra', models.IntegerField()),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
                ('nitProveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribuidor.Distribuidor')),
            ],
        ),
    ]
