# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='codigoCompra',
            new_name='codigo_compra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='idProducto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='nitProveedor',
            new_name='nit_proveedor',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='valorCompra',
            new_name='valor_compra',
        ),
    ]
