# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20171001_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioCosto',
            field=models.IntegerField(null=True),
        ),
    ]
