# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20171022_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_producto',
            new_name='idProducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_producto',
            new_name='precioProducto',
        ),
    ]
