# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20171023_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precio_producto',
        ),
    ]
