# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('nitDistribuidor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreDistribuidor', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
