# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidor',
            old_name='nitDistribuidor',
            new_name='nit_distribuidor',
        ),
    ]
