# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0002_auto_20171022_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidor',
            old_name='nombreDistribuidor',
            new_name='nombre_distribuidor',
        ),
    ]
