# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0003_auto_20171022_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribuidor',
            old_name='nit_distribuidor',
            new_name='nitDistribuidor',
        ),
        migrations.RenameField(
            model_name='distribuidor',
            old_name='nombre_distribuidor',
            new_name='nombreDistribuidor',
        ),
    ]
