# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0005_auto_20171023_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
