# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20171022_1812'),
        ('registro', '0003_auto_20171022_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
