# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20171119_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name=b'19-11-17 22:24 49'),
        ),
    ]
